
pipeline {
      environment {
    dotnet = './sample-mvc'
  }
        agent any

    stages {
        stage('Restore') {
            steps {
                sh 'dotnet restore $dotnet'
            }
        }
        stage('Build') {
            steps {
                    sh 'dotnet build $dotnet'
                
            }
        }
        stage('Test') {
            steps {
                    sh 'dotnet test $dotnet'
            }
        }
                stage('build and push') {
            steps {
                                    script {
                        docker.withRegistry('https://registry-1.docker.io/v2/', 'dockerhubCredential'){
                            def dockerImage = docker.image('<dockerhub>')
                            dockerImage.push()
                        }
                    }
            }
        }
        
                        stage('deploy') {
            steps {
                    sh "docker-compose up --build -d"
            }
        }
    }
}